# Jekyll configuration precedence:
# 1. Gulp task
# 2. config.build.yml
# 3. config.yml

name: mvrt-website
description: MVRT's snazzy new website.

# Gulp handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess', 'favicon.ico']

keep_files: ['img']

# _config.build.yml sets future and show_drafts to false on `gulp dist`
future: true
show_drafts: true

# Markdown library
markdown: kramdown

kramdown:
  auto_ids: true
  use_coderay: false

paginate: 5
paginate_path: "blog/page:num/"
highlighter: rouge

permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

permalink: /blog/:year/:month/:title/
